"""create initial backend schema

Revision ID: 6c6f1a618821
Revises: 
Create Date: 2026-04-09 21:09:39.909795
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6f1a618821'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('prediction_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_sessions_status'), 'prediction_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_prediction_sessions_user_id'), 'prediction_sessions', ['user_id'], unique=False)
    op.create_table('prediction_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('predicted_label', sa.String(length=100), nullable=False),
    sa.Column('arabic_label', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('top_predictions_json', sa.JSON(), nullable=False),
    sa.Column('raw_landmarks_json', sa.JSON(), nullable=True),
    sa.Column('client_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['prediction_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_records_created_at'), 'prediction_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_prediction_records_predicted_label'), 'prediction_records', ['predicted_label'], unique=False)
    op.create_index(op.f('ix_prediction_records_session_id'), 'prediction_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_prediction_records_user_id'), 'prediction_records', ['user_id'], unique=False)
    op.create_table('saved_phrases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_session_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_session_id'], ['prediction_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_phrases_source_session_id'), 'saved_phrases', ['source_session_id'], unique=False)
    op.create_index(op.f('ix_saved_phrases_user_id'), 'saved_phrases', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('prediction_record_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('expected_label', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_record_id'], ['prediction_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['prediction_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_prediction_record_id'), 'feedback', ['prediction_record_id'], unique=False)
    op.create_index(op.f('ix_feedback_session_id'), 'feedback', ['session_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_session_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_prediction_record_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_saved_phrases_user_id'), table_name='saved_phrases')
    op.drop_index(op.f('ix_saved_phrases_source_session_id'), table_name='saved_phrases')
    op.drop_table('saved_phrases')
    op.drop_index(op.f('ix_prediction_records_user_id'), table_name='prediction_records')
    op.drop_index(op.f('ix_prediction_records_session_id'), table_name='prediction_records')
    op.drop_index(op.f('ix_prediction_records_predicted_label'), table_name='prediction_records')
    op.drop_index(op.f('ix_prediction_records_created_at'), table_name='prediction_records')
    op.drop_table('prediction_records')
    op.drop_index(op.f('ix_prediction_sessions_user_id'), table_name='prediction_sessions')
    op.drop_index(op.f('ix_prediction_sessions_status'), table_name='prediction_sessions')
    op.drop_table('prediction_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
